---
apiVersion: v2
name: fadi
version: 0.2.4
appVersion: 0.2.4
description: FADI is a Cloud Native platform for Big Data based on mature open source tools. 
keywords:
  - fadi
  - cetic
  - bigdata
  - nifi
  - spark
  - grafana
  - cassandra
  - kafka
home: https://github.com/cetic/fadi
icon: https://raw.githubusercontent.com/cetic/fadi/master/doc/images/logo.png
source:
  - https://github.com/cetic/fadi
maintainers:
  - name: alexnuttinck
  - name: banzo
  - name: AyadiAmen
dependencies:
- name: spark
  version: ~1.0.3
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: spark.enabled
- name: superset
  version: ~1.1.11
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: superset.enabled
- name: postgresql
  version: ~0.2.0
  repository: https://cetic.github.io/helm-charts/
  condition: postgresql.enabled
- name: minio
  version: ~5.0.29
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: minio.enabled
- name: grafana
  version: ~5.2.0
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: grafana.enabled
- name: jupyterhub
  version: ~0.9.0
  repository: https://jupyterhub.github.io/helm-chart/
  condition: jupyterhub.enabled
- name: nifi
  version: ~0.4.2
  repository: https://cetic.github.io/helm-charts/
  condition: nifi.enabled
- name: openldap
  version: ~1.2.4
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: openldap.enabled
- name: phpldapadmin
  version: ~0.1.3
  repository: https://cetic.github.io/helm-charts/
  condition: phpldapadmin.enabled
- name: kafka
  version: ~0.21.2
  repository: https://kubernetes-charts-incubator.storage.googleapis.com
  condition: kafka.enabled
- name: cassandra
  version: ~0.15.1
  repository: https://kubernetes-charts-incubator.storage.googleapis.com
  condition: cassandra.enabled
- name: elasticsearch
  version: ^1.22.0
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: elasticsearch.enabled
- name: kibana
  version: ^3.0.0
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: kibana.enabled
- name: filebeat
  version: ^4.0.0
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: filebeat.enabled
- name: logstash
  version: ^2.4.0
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: logstash.enabled
- name: tsaas
  version: ^0.1.3
  repository: https://cetic.github.io/helm-charts/
  condition: tsaas.enabled
- name: swaggerui
  version: ^0.3.1
  repository: https://cetic.github.io/helm-charts/
  condition: swaggerui.enabled
- name: nginx-ldapauth-proxy
  version: ^0.1.3
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: nginx_ldapauth_proxy.enabled
- name: node-red
  version: ^1.4.0
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: node-red.enabled
- name: adminer
  version: ~0.1.3
  repository: https://cetic.github.io/helm-charts/
  condition: adminer.enabled
- name: mlflow
  version: ~1.4.0
  repository: https://cetic.github.io/helm-charts/
  condition: mlflow.enabled
- name: zabbix
  version: ~0.1.2
  repository: https://cetic.github.io/helm-charts/
  condition: zabbix.enabled
- name: seldon-core-operator
  version: ~1.0.2
  repository: https://storage.googleapis.com/seldon-charts/
  condition: seldon-core-operator.enabled