name: fadi
version: 0.1.2
appVersion: 0.1.2
description: FADI is a Cloud Native platform for Big Data based on mature open source tools. 
keywords:
  - fadi
  - bigdata
  - nifi
  - spark
  - grafana
home: https://github.com/cetic/fadi
icon: https://github.com/cetic/fadi/blob/master/doc/images/logo.png
source:
  - https://github.com/cetic/fadi
maintainers:
  - name: alexnuttinck
  - name: banzo
