---
apiVersion: v2
name: fadi
version: 0.3.0
appVersion: 0.3.0
description: FADI is a Cloud Native platform for Big Data based on mature open source tools. 
keywords:
  - fadi
  - cetic
  - bigdata
  - nifi
  - spark
  - grafana
  - cassandra
  - kafka
  - mongodb
home: https://github.com/cetic/fadi
icon: https://raw.githubusercontent.com/cetic/fadi/master/doc/images/logo.png
source:
  - https://github.com/cetic/fadi
maintainers:
  - name: alexnuttinck
  - name: banzo
  - name: AyadiAmen
dependencies:
- name: spark
  version: ~4.1.0
  repository: https://charts.bitnami.com/bitnami
  condition: spark.enabled
- name: superset
  version: ~1.2.0
  repository: https://charts.cloudposse.com/incubator/
  condition: superset.enabled
- name: postgresql
  version: ~0.2.1
  repository: https://cetic.github.io/helm-charts/
  condition: postgresql.enabled
- name: minio
  version: ~8.0.5
  repository: https://helm.min.io/
  condition: minio.enabled
- name: grafana
  version: ~5.2.4
  repository: https://charts.bitnami.com/bitnami
  condition: grafana.enabled
- name: jupyterhub
  version: ~0.11.1
  repository: https://jupyterhub.github.io/helm-chart/
  condition: jupyterhub.enabled
- name: nifi
  version: ~1.0.6
  repository: https://cetic.github.io/helm-charts/
  condition: nifi.enabled
- name: openldap
  version: ~1.2.4
  repository: https://charts.helm.sh/stable
  condition: openldap.enabled
- name: phpldapadmin
  version: ~0.1.3
  repository: https://cetic.github.io/helm-charts/
  condition: phpldapadmin.enabled
- name: kafka
  version: ~12.2.1
  repository: https://charts.bitnami.com/bitnami
  condition: kafka.enabled
- name: cassandra
  version: ~7.0.1
  repository: https://charts.bitnami.com/bitnami
  condition: cassandra.enabled
- name: elasticsearch
  version: ^7.10.0
  repository: https://helm.elastic.co
  condition: elasticsearch.enabled
- name: kibana
  version: ^7.10.0
  repository: https://helm.elastic.co
  condition: kibana.enabled
- name: filebeat
  version: ^7.10.0
  repository: https://helm.elastic.co
  condition: filebeat.enabled
- name: logstash
  version: ^7.10.0
  repository: https://helm.elastic.co
  condition: logstash.enabled
- name: tsaas
  version: ^0.1.3
  repository: https://cetic.github.io/helm-charts/
  condition: tsaas.enabled
- name: swaggerui
  version: ^0.3.1
  repository: https://cetic.github.io/helm-charts/
  condition: swaggerui.enabled
- name: adminer
  version: ~0.1.3
  repository: https://cetic.github.io/helm-charts/
  condition: adminer.enabled
- name: mlflow
  version: ~1.5.0
  repository: https://cetic.github.io/helm-charts/
  condition: mlflow.enabled
- name: zabbix
  version: ~0.3.2
  repository: https://cetic.github.io/helm-charts/
  condition: zabbix.enabled
- name: seldon-core-operator
  version: ~1.0.2
  repository: https://storage.googleapis.com/seldon-charts/
  condition: seldon-core-operator.enabled
- name: drupal
  version: ~0.1.0
  repository: https://cetic.github.io/helm-charts/
  condition: drupal.enabled
- name: airflow
  version: ~9.0.0
  repository: https://charts.bitnami.com/bitnami
  condition: airflow.enabled
- name: rabbitmq
  version: ~8.11.5
  repository: https://charts.bitnami.com/bitnami
  condition: rabbitmq.enabled
- name: thingsboard
  version: ~0.1.1
  repository: https://cetic.github.io/helm-charts/
  condition: thingsboard.enabled
- name: mongodb
  version: ~10.11.1
  repository: https://charts.bitnami.com/bitnami
  condition: mongodb.enabled
- name: influxdb
  version: ^2.3.18
  repository: https://charts.bitnami.com/bitnami
  condition: influxdb.enabled
- name: traefik
  version: ~10.6.2
  repository: https://helm.traefik.io/traefik
  condition: traefik.enabled
- name: cert-manager
  version: ~1.7.1
  repository: https://charts.jetstack.io
  condition: cert-manager.enabled
- name: keycloak
  version: ~2.4.7
  repository: https://charts.bitnami.com/bitnami
  condition: keycloak.enabled