name: fadi
version: 0.1.15
appVersion: 0.1.15
description: FADI is a Cloud Native platform for Big Data based on mature open source tools. 
keywords:
  - fadi
  - cetic
  - bigdata
  - nifi
  - spark
  - grafana
  - cassandra
  - kafka
home: https://github.com/cetic/fadi
icon: https://raw.githubusercontent.com/cetic/fadi/master/doc/images/logo.png
source:
  - https://github.com/cetic/fadi
maintainers:
  - name: alexnuttinck
  - name: banzo
  - name: AyadiAmen
