---
dependencies:
- name: spark
  version: ~1.0.0
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: spark.enabled
- name: superset
  version: ~1.1.6
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: superset.enabled
- name: postgresql
  version: ~0.1.0
  repository: https://cetic.github.io/helm-charts/
  condition: postgresql.enabled
- name: minio
  version: ~2.4.18
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: minio.enabled
- name: grafana
  version: ~3.5.4
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: grafana.enabled
- name: jupyterhub
  version: ~0.8.0
  repository: https://jupyterhub.github.io/helm-chart/
  condition: jupyterhub.enabled
- name: nifi
  version: ~0.1.6
  repository: https://cetic.github.io/helm-charts/
  condition: nifi.enabled
- name: pgadmin
  version: ~0.1.8
  repository: https://cetic.github.io/helm-charts/
  condition: pgadmin.enabled
- name: openldap
  version: ~1.1.0
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: openldap.enabled
- name: phpldapadmin
  version: ~0.1.2
  repository: https://cetic.github.io/helm-charts/
  condition: phpldapadmin.enabled
- name: elastic-stack
  version: ~1.8.0
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: elasticstack.enabled
- name: kafka
  version: ~0.1.2
  repository: https://kubernetes-charts-incubator.storage.googleapis.com
  condition: kafka.enabled
- name: cassandra
  version: ~0.13.2
  repository: https://kubernetes-charts-incubator.storage.googleapis.com
  condition: cassandra.enabled
