{{- if .Values.networkPolicy.enabled }}
kind: NetworkPolicy
apiVersion: {{ template "influxdb.networkPolicy.apiVersion" . }}
metadata:
  name: {{ include "common.names.fullname" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  podSelector:
    matchLabels:  {{ include "common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: influxdb
  policyTypes:
    - Ingress
  ingress:
    # Allow inbound connections
    - ports:
        - port: {{ .Values.influxdb.containerPorts.http }}
          protocol: TCP
        - port: {{ .Values.influxdb.containerPorts.rpc }}
          protocol: TCP
      {{- if not .Values.networkPolicy.allowExternal }}
      from:
        - podSelector:
            matchLabels:
              {{ template "common.names.fullname" . }}-client: "true"
        {{- if eq .Values.architecture "high-availability" }}
        - podSelector:
            matchLabels: {{- include "common.labels.matchLabels" . | nindent 14 }}
              app.kubernetes.io/component: relay
        {{- end }}
      {{- end }}
{{- end }}
