{{- if eq .Values.architecture "high-availability" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}-relay
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: relay
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if or .Values.relay.service.annotations .Values.commonAnnotations }}
  annotations:
  {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
  {{- if .Values.relay.service.annotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.relay.service.annotations "context" $) | nindent 4 }}
  {{- end }}
  {{- end }}
spec:
  type: {{ .Values.relay.service.type }}
  {{- if and .Values.relay.service.loadBalancerIP (eq .Values.relay.service.type "LoadBalancer") }}
  loadBalancerIP: {{ .Values.relay.service.loadBalancerIP }}
  {{- end }}
  {{- if and (eq .Values.relay.service.type "LoadBalancer") .Values.relay.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
  {{ with .Values.relay.service.loadBalancerSourceRanges }}
{{ toYaml . | indent 4 }}
  {{- end }}
  {{- end }}
  {{- if and (eq .Values.relay.service.type "ClusterIP") .Values.relay.service.clusterIP }}
  clusterIP: {{ .Values.relay.service.clusterIP }}
  {{- end }}
  ports:
    - port: {{ .Values.relay.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if (and (or (eq .Values.relay.service.type "NodePort") (eq .Values.relay.service.type "LoadBalancer")) (not (empty .Values.relay.service.nodePort)))}}
      nodePort: {{ .Values.relay.service.nodePort }}
      {{- else if eq .Values.relay.service.type "ClusterIP" }}
      nodePort: null
      {{- end }}
  selector:
    {{- include "common.labels.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: relay
{{- end }}
