apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: grafana
spec:
  entryPoints:
    - web
  routes:
  - kind: Rule
    match: Host(`grafana.test.local`) && PathPrefix(`/`)
    services:
    - name: fadi-grafana
      port: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: nifi
spec:
  entryPoints:
    - websecure
  routes:
  - match: HostSNI(`nifi.test.local`)
    services:
      - name: fadi-nifi
        port: 9443
  tls:
    passthrough: true