{{- if .Values.traefik.enabled -}}
{{- if and (.Values.grafana.enabled) (.Values.grafana.traefikIngress.enabled) -}}
{{- if .Values.grafana.traefikIngress.tls }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: grafana
spec:
  entryPoints:
    - websecure
  routes:
  - kind: Rule
    match: Host(`{{ .Values.grafana.traefikIngress.host }}`) && PathPrefix(`/`)
    services:
      - name: {{ .Release.Name }}-grafana
        port: 80
  tls:
    secretName: {{ .Values.grafana.traefikIngress.host }}  
---
{{- end }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: grafana-http
spec:
  entryPoints:
    - web
  routes:
  - kind: Rule
    match: Host(`{{ .Values.grafana.traefikIngress.host }}`) && PathPrefix(`/`)
    services:
    - name: {{ .Release.Name }}-grafana
      port: 80
    {{- if .Values.grafana.traefikIngress.tls }}
    middlewares:
      - name: https-redirect
    {{- end }}
---
{{- end }}

{{- if and (.Values.nifi.enabled) (.Values.nifi.traefikIngress.enabled) -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: nifi
spec:
  entryPoints:
    - websecure
  routes:
  - match: HostSNI(`{{ .Values.nifi.traefikIngress.host }}`)
    services:
      - name: {{ .Release.Name }}-nifi
        port: {{ .Values.nifi.properties.httpsPort }}
  tls:
    passthrough: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: nifi-http
spec:
  entryPoints:
    - web
  routes:
  - kind: Rule
    match: Host(`{{ .Values.nifi.traefikIngress.host }}`) && PathPrefix(`/`)
    services:
      - name: {{ .Release.Name }}-nifi
        port: {{ .Values.nifi.properties.httpsPort }}
    middlewares:
      - name: https-redirect
---
{{- end }}

{{- if and (.Values.jupyterhub.enabled) (.Values.jupyterhub.traefikIngress.enabled) -}}
{{- if .Values.jupyterhub.traefikIngress.tls }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: hub
spec:
  entryPoints:
    - websecure
  routes:
  - kind: Rule
    match: Host(`{{ .Values.jupyterhub.traefikIngress.host }}`) && PathPrefix(`/`)
    services:
    - name: proxy-public
      port: 80
  tls:
    secretName: {{ .Values.jupyterhub.traefikIngress.host }}
---
{{- end }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: hub-http
spec:
  entryPoints:
    - web
  routes:
  - kind: Rule
    match: Host(`{{ .Values.jupyterhub.traefikIngress.host }}`) && PathPrefix(`/`)
    services:
    - name: proxy-public
      port: 80
    {{- if .Values.jupyterhub.traefikIngress.tls }}
    middlewares:
      - name: https-redirect
    {{- end }}
---
{{- end }}

{{- if .Values.traefik.dashboardIngress.enabled -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: dashboard
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`{{ .Values.traefik.dashboardHost }}`)
      kind: Rule
      services:
        - name: api@internal
          kind: TraefikService
---
{{- end }}

{{- if and (.Values.superset.enabled) (.Values.superset.traefikIngress.enabled) -}}
{{- if .Values.superset.traefikIngress.tls }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: superset
spec:
  entryPoints:
    - websecure
  routes:
  - kind: Rule
    match: Host(`{{ .Values.superset.traefikIngress.host }}`) && PathPrefix(`/`)
    services:
    - name: {{ .Release.Name }}-superset
      port: 9000
  tls:
    secretName: {{ .Values.superset.traefikIngress.host }}
---
{{- end }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: superset-http
spec:
  entryPoints:
    - web
  routes:
  - kind: Rule
    match: Host(`{{ .Values.superset.traefikIngress.host }}`) && PathPrefix(`/`)
    services:
    - name: {{ .Release.Name }}-superset
      port: 9000
    {{- if .Values.superset.traefikIngress.tls }}
    middlewares:
      - name: https-redirect
    {{- end }}
---
{{- end }}

{{- if and (.Values.keycloak.enabled) (.Values.keycloak.traefikIngress.enabled) -}}
{{- if .Values.keycloak.traefikIngress.tls }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: keycloak
spec:
  entryPoints:
    - websecure
  routes:
  - kind: Rule
    match: Host(`{{ .Values.keycloak.traefikIngress.host }}`) && PathPrefix(`/`)
    services:
      - name: {{ .Release.Name }}-keycloak
        port: 80
  tls:
    secretName: {{ .Values.keycloak.traefikIngress.host }}  
---
{{- end }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: keycloak-http
spec:
  entryPoints:
    - web
  routes:
  - kind: Rule
    match: Host(`{{ .Values.keycloak.traefikIngress.host }}`) && PathPrefix(`/`)
    services:
    - name: {{ .Release.Name }}-keycloak
      port: 80
    {{- if .Values.keycloak.traefikIngress.tls }}
    middlewares:
      - name: https-redirect
    {{- end }}
---
{{- end }}

{{- if .Values.clusterIssuer.enabled }}
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: https-redirect
spec:
  redirectScheme:
    scheme: https
    permanent: true
{{- end }}

{{- end }}
